service: message-lista-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentBucket:
    name: philip-bucket-examination
  environment:
    USERS_TABLE: messages # Ensure this is set correctly
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem # Added this to allow updates
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/messages # Adjust if necessary

functions:
  app:
    handler: handler.handler # Point to the exported handler for the Express app
    events:
      - http:
          path: users/{userId} # GET user by userId
          method: get
          cors: true
      - http:
          path: users # POST user
          method: post
          cors: true
      - http:
          path: messages # GET messages
          method: get
          cors: true
      - http:
          path: messages # POST messages
          method: post
          cors: true
      - http:
          path: messages/{id} # PUT to update messages by ID
          method: put
          cors: true # Added PUT method for updating messages

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
